#default: &default
#  adapter: sqlite3
#  pool: <%#= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  timeout: 5000

#development:
#  <<: *default
#  database: db/development.sqlite3

#test:
#  <<: *default
#  database: db/test.sqlite3

#production:
#  adapter: postgresql
#  encoding: unicode
#  pool: <%#= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  database: sample_app_production
#  username: sample_app
#  password: <%#= ENV['SAMPLE_APP_DATABASE_PASSWORD'] %>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  database: sample_rails_app_7th_ed
  username: postgres
  password:

development:
  <<: *default
  database: sample_rails_app_7th_ed_dev

test:
  <<: *default
  database: sample_rails_app_7th_ed_test